name: sure_predict
description: Sure Predict - Football predictions
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# IMPORTANT: Fix pentru erorile win32/file/ffi cu lock vechi / Dart 3.5
dependency_overrides:
  win32: 5.5.0
  ffi: 2.1.2
  file: 7.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/app_ro.arb
    - lib/l10n/app_en.arb
